api:
  authKey: 9ee19d53-64db-4d91-9f3f-62029f3d0ecd
  seed: "SSGREALKEY"
  allowIps: ['127.0.0.1','10.149.181.203','10.203.7.71']

---

spring:
  profiles: prod
  seed: "SSGREALKEY"
  
---

spring:
  profiles: qa
  seed: "SSGQAKEY"

---

spring:
  profiles: dev
  seed: "SSGDEVKEY"
  
---

spring:
  profiles: local
  seed: "SSGLOCALKEY"
