api:
  authKey: 5kr12349-5w88-1h23-aad4-273je42h38ei
  seed: "SSGREALKEY"
  prodSeed: "SSGPRODKEY"
  qaSeed: "SSGQAKEY"
  testIps: ['127.0.0.1','10.149.181.203','10.203.7.71','10.149.181.229','10.149.181.224','10.149.181.185','10.149.181.178']
  qaIps: ['127.0.0.1']
  prodIps: ['127.0.0.1']

---

spring:
  profiles: prod
  seed: "SSGREALKEY"
  
---

spring:
  profiles: qa
  seed: "SSGQAKEY"

---

spring:
  profiles: dev
  seed: "SSGDEVKEY"
  
---

spring:
  profiles: local
  seed: "SSGLOCALKEY"
